export const pairs = {
  mollë: "apple",
  laps: "pencil",
  zjarr: "fire",
  tigër: "tiger",
  shkrepëse: "matches",
  lule: "flower",
  libër: "book",
  stol: "chair",
  tavolinë: "table",
  dritare: "window",
  derë: "door",
  pirun: "fork",
  thikë: "knife",
  gotë: "glass",
  buzë: "lip",
  dhëmb: "tooth",
  gjuhë: "tongue",
  gjoksi: "chest",
  dorë: "hand",
  sy: "eye",
  vesh: "ear",
  kokë: "head",
  flokë: "hair",
  vetull: "eyebrow",
  hundë: "nose",
  sqep: "beak",
  krah: "arm",
  bark: "stomach",
  gju: "knee",
  dhëmbë: "teeth",
  gishta: "fingers",
  thonjtë: "fingernails",
  këmbë: "leg",
  mish: "meat",
  kripë: "salt",
  miell: "flour",
  uthull: "vinegar",
  çokollatë: "chocolate",
  krahë: "wings",
  shpatë: "sword",
  çekiç: "hammer",
  sopatë: "axe",
  shishe: "bottle",
  kimik: "pen",
  gërshërë: "scissors",
  kanaçe: "can",
  spec: "paprika",
  gjysmë: "half",
  pjesë: "part",
  vijë: "line",
  vizatim: "drawing",
  pikturë: "painting",
  ngjyrë: "color",
  numër: "number",
  shkronjë: "letter",
  fjalë: "word",
  histori: "story",
  trekëndësh: "triangle",
  katror: "square",
  rreth: "circle",
  kënd: "angle",
  majë: "tip",
  lartësi: "height",
  gjerësi: "width",
  mes: "between",
  jo: "no",
  po: "yes",
  unë: "I",
  ti: "you",
  ai: "he",
  ajo: "she",
  ne: "we",
  ju: "you",
  ata: "they",
  një: "one",
  që: "that",
  dhe: "and",
  në: "in",
  mbi: "on",
  mua: "me",
  asaj: "her",
  ashtu: "so",
  këtu: "here",
  atje: "there",
  kudo: "anywhere",
  këdo: "anyone",
  tani: "now",
  pastaj: "then",
  mbrëmje: "evening",
  natë: "night",
  gjumë: "sleep",
  koha: "time",
  kohë: "time",
  ditë: "day",
  javë: "week",
  muaj: "month",
  viti: "year",
  orë: "hour",
  minutë: "minute",
  sekondë: "second",
};

export const roleplayQuestions = [
  {
    question: "Si e ke emrin?",
    answers: [
      "Unë quhem Beni.",
      "Emri im është Beni.",
      "Unë jam student.",
      "Beni.",
    ],
    correctAnswers: [0, 1, 3],
  },
  {
    question: "Sa vjeç je?",
    answers: ["5", "Pesë.", "Jam pesë vjeç.", "Jo."],
    correctAnswers: [0, 1, 2],
  },
];
